<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Speckle.Objects" Version="2026.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdaptiveNetwork.Geometry.Core\AdaptiveNetwork.Geometry.Core.csproj" />
  </ItemGroup>

</Project>
